export type Tier = "free" | "lite" | "pro";
export type PermissionAction = "view" | "edit" | "delete" | "admin";

export interface PermissionDef {
  key: string;
  name: string;
  desc: string;
  tier: Tier;
  action: PermissionAction;
  backendFeatureKey: string;
  backendAction: string;
}

export interface PermissionGroup {
  id: string;
  label: string;
  category: string;
  description: string;
  permissions: PermissionDef[];
}

export const PERMISSION_GROUPS: PermissionGroup[] = [
  {
    id: "rooms",
    label: "Rooms & Inventory",
    category: "tenant_management",
    description: "Floor plans, room configurations, bed slots, and live occupancy",
    permissions: [
      {
        key: "room_view",
        name: "View Rooms & Inventory",
        desc: "See all rooms, beds, occupancy, room rates, and share room links",
        tier: "free",
        action: "view",
        backendFeatureKey: "room_management",
        backendAction: "read",
      },
      {
        key: "room_add",
        name: "Add Rooms & Beds",
        desc: "Create new rooms, floors, and bed slots in the property layout",
        tier: "free",
        action: "edit",
        backendFeatureKey: "room_management",
        backendAction: "create",
      },
      {
        key: "room_edit",
        name: "Edit Room Details",
        desc: "Update room type, capacity, monthly rent rate, and amenities",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "room_management",
        backendAction: "update",
      },
      {
        key: "room_delete",
        name: "Delete Rooms & Beds",
        desc: "Permanently remove a room or bed configuration",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "room_management",
        backendAction: "delete",
      },
    ],
  },
  {
    id: "tenants",
    label: "Tenants & Onboarding",
    category: "tenant_management",
    description: "Tenant profiles, room allocation, check-in, contact details, and notices",
    permissions: [
      {
        key: "tenant_view",
        name: "View Tenants & Bookings",
        desc: "See tenant roster, profiles, stay history, and room allocations (Read-only for cleaners/guards)",
        tier: "free",
        action: "view",
        backendFeatureKey: "tenant_management",
        backendAction: "read",
      },
      {
        key: "tenant_add",
        name: "Add New Tenant / Booking",
        desc: "Onboard new tenants, create booking agreements, allocate room and bed",
        tier: "free",
        action: "edit",
        backendFeatureKey: "manual_tenant_add",
        backendAction: "create",
      },
      {
        key: "tenant_edit_basic",
        name: "Edit Tenant Details (Basic)",
        desc: "Update tenant name, contact numbers, email, photo, and emergency contacts",
        tier: "free",
        action: "edit",
        backendFeatureKey: "tenant_management",
        backendAction: "update",
      },
      {
        key: "tenant_edit_rental",
        name: "Edit Rental & Financial Terms",
        desc: "Modify rent amount, security deposit, due dates, and billing cycles",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "tenant_management",
        backendAction: "update",
      },
      {
        key: "tenant_change_room",
        name: "Change Room & Bed Allocation",
        desc: "Shift tenant to a different room, floor, or sister property",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "tenant_room_mapping",
        backendAction: "update",
      },
      {
        key: "tenant_opening_balance",
        name: "Manage Opening Balances",
        desc: "Set initial balance or adjust carryover dues during onboarding",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "rent_management",
        backendAction: "update",
      },
      {
        key: "tenant_delete",
        name: "Delete / Checkout Tenant",
        desc: "Remove active tenant record or trigger full exit checklist",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "tenant_management",
        backendAction: "delete",
      },
      {
        key: "tenant_delete_old",
        name: "Purge Archived Tenant Records",
        desc: "Permanently delete historical and exited tenant data",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "tenant_management",
        backendAction: "delete",
      },
    ],
  },
  {
    id: "accounting",
    label: "Accounting & Rent Ledger",
    category: "payment",
    description: "Rent collections, payment receipts, dues tracking, and financial transactions",
    permissions: [
      {
        key: "account_view_dues",
        name: "View Rent & Dues Ledger",
        desc: "See who has paid, pending dues, collection totals, and bank payments (Hideable from Caretaker/Cleaner)",
        tier: "lite",
        action: "view",
        backendFeatureKey: "rent_management",
        backendAction: "read",
      },
      {
        key: "account_view_own_dues",
        name: "View Own Recorded Dues",
        desc: "See only dues and collections logged directly by this staff member",
        tier: "free",
        action: "view",
        backendFeatureKey: "manual_rent_tracking",
        backendAction: "read",
      },
      {
        key: "account_record_payment",
        name: "Record Payment Collection",
        desc: "Mark cash, UPI, or bank transfer payments as collected and issue receipt",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "manual_payment_verify",
        backendAction: "create",
      },
      {
        key: "account_add_dues",
        name: "Create / Add Due Charges",
        desc: "Create rent, electricity, maintenance, or penalty dues for tenants",
        tier: "free",
        action: "edit",
        backendFeatureKey: "manual_rent_tracking",
        backendAction: "create",
      },
      {
        key: "account_edit_dues",
        name: "Edit Dues & Waive Late Fees",
        desc: "Modify due amount, adjust payment dates, or waive late penalty fees",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "late_fee_management",
        backendAction: "update",
      },
      {
        key: "account_delete_dues",
        name: "Delete Due & Payment Records",
        desc: "Permanently remove a due entry or void a payment transaction",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "rent_management",
        backendAction: "delete",
      },
      {
        key: "account_send_reminders",
        name: "Send WhatsApp Rent Reminders",
        desc: "Send automated or one-click WhatsApp/SMS payment reminders to tenants",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "whatsapp_rent_reminders",
        backendAction: "execute",
      },
      {
        key: "account_otp_cash",
        name: "Cash Collection OTP Verification",
        desc: "Authenticate cash handover securely using one-time verification password",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "manual_payment_verify",
        backendAction: "update",
      },
    ],
  },
  {
    id: "expenses",
    label: "Expenses & Petty Cash",
    category: "payment",
    description: "Property expenses, maintenance costs, utilities, and vendor payouts",
    permissions: [
      {
        key: "expense_view",
        name: "View Expenses Ledger",
        desc: "See all logged property expenses, vendor invoices, and category breakdowns",
        tier: "lite",
        action: "view",
        backendFeatureKey: "expense_tracking",
        backendAction: "read",
      },
      {
        key: "expense_add",
        name: "Log New Expense",
        desc: "Create expense entry for repairs, groceries, utilities, or staff salaries",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "expense_tracking",
        backendAction: "create",
      },
      {
        key: "expense_edit",
        name: "Edit Expense Record",
        desc: "Modify expense amount, date, vendor, category, or receipt voucher",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "expense_tracking",
        backendAction: "update",
      },
      {
        key: "expense_delete",
        name: "Delete Expense",
        desc: "Remove an expense entry from the financial ledger",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "expense_tracking",
        backendAction: "delete",
      },
    ],
  },
  {
    id: "complaints",
    label: "Complaints & Maintenance",
    category: "support",
    description: "Tenant complaints desk, ticket assignment, SLA tracking, and resolution",
    permissions: [
      {
        key: "complaint_view_all",
        name: "View All Complaints",
        desc: "See every maintenance, plumbing, electrical, and food complaint from all tenants",
        tier: "free",
        action: "view",
        backendFeatureKey: "complaint_management",
        backendAction: "read",
      },
      {
        key: "complaint_view_own",
        name: "View Assigned / Own Complaints",
        desc: "See only complaints assigned to this staff member or raised by them",
        tier: "free",
        action: "view",
        backendFeatureKey: "complaint_management",
        backendAction: "read",
      },
      {
        key: "complaint_raise",
        name: "Raise New Complaint",
        desc: "Log a maintenance issue on behalf of a tenant or for common areas",
        tier: "free",
        action: "edit",
        backendFeatureKey: "complaint_management",
        backendAction: "create",
      },
      {
        key: "complaint_edit_assign",
        name: "Edit, Assign & Resolve Complaints",
        desc: "Assign complaints to staff, update status, add comments, and close tickets",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "complaint_assignment",
        backendAction: "update",
      },
      {
        key: "complaint_edit_own",
        name: "Update Own Complaints",
        desc: "Update progress or close tickets raised by self",
        tier: "free",
        action: "edit",
        backendFeatureKey: "complaint_management",
        backendAction: "update",
      },
    ],
  },
  {
    id: "food",
    label: "Food Menu & Dining",
    category: "support",
    description: "Daily breakfast, lunch, and dinner menus, meal timings, and dietary notices",
    permissions: [
      {
        key: "food_view",
        name: "View Food Menu",
        desc: "See daily and weekly food menus, timings, and dining schedules",
        tier: "free",
        action: "view",
        backendFeatureKey: "food_menu",
        backendAction: "read",
      },
      {
        key: "food_edit",
        name: "Edit Food Menu",
        desc: "Update breakfast, lunch, dinner items, meal timings, and special announcements",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "food_menu",
        backendAction: "update",
      },
      {
        key: "food_view_edit",
        name: "View & Edit Food Menu (Legacy)",
        desc: "Combined view and edit access for food planning",
        tier: "free",
        action: "edit",
        backendFeatureKey: "food_menu",
        backendAction: "update",
      },
    ],
  },
  {
    id: "attendance",
    label: "Attendance & Check-in",
    category: "support",
    description: "Tenant daily presence, biometric/manual check-in, and leave requests",
    permissions: [
      {
        key: "attend_view",
        name: "View Attendance Records",
        desc: "View attendance logs, daily presence sheets, and tenant absence history",
        tier: "free",
        action: "view",
        backendFeatureKey: "meal_tracking",
        backendAction: "read",
      },
      {
        key: "attend_mark",
        name: "Mark Tenant Attendance",
        desc: "Record daily tenant presence, absence, or mark check-in manually",
        tier: "free",
        action: "edit",
        backendFeatureKey: "meal_tracking",
        backendAction: "create",
      },
      {
        key: "attend_leave",
        name: "Approve Leave Requests",
        desc: "Approve or decline tenant leave notifications and vacation dates",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "meal_tracking",
        backendAction: "update",
      },
    ],
  },
  {
    id: "nightout",
    label: "Night Out & Curfew Passes",
    category: "support",
    description: "Overnight permissions, late entry passes, parent intimation, and return logs",
    permissions: [
      {
        key: "nightout_view",
        name: "View Night Out Requests",
        desc: "See all pending, active, approved, and returned night out records",
        tier: "free",
        action: "view",
        backendFeatureKey: "guest_tracking",
        backendAction: "read",
      },
      {
        key: "nightout_approve",
        name: "Approve / Deny Night Out",
        desc: "Grant or reject tenant night out requests and set curfew limits",
        tier: "free",
        action: "edit",
        backendFeatureKey: "guest_tracking",
        backendAction: "update",
      },
      {
        key: "nightout_mark_returned",
        name: "Mark Tenant Returned",
        desc: "Confirm tenant has arrived back safely and close nightout pass",
        tier: "free",
        action: "edit",
        backendFeatureKey: "guest_tracking",
        backendAction: "update",
      },
      {
        key: "nightout_extend",
        name: "Approve Curfew Extension",
        desc: "Approve late return requests or multi-day extension",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "guest_tracking",
        backendAction: "update",
      },
      {
        key: "outing_approve",
        name: "Approve Short Outing",
        desc: "Approve daytime or short evening outing passes",
        tier: "free",
        action: "edit",
        backendFeatureKey: "guest_tracking",
        backendAction: "update",
      },
      {
        key: "nightout_report",
        name: "Night Out & Overstay Reports",
        desc: "Export nightout logs and track unauthorized late returns",
        tier: "lite",
        action: "view",
        backendFeatureKey: "basic_reports",
        backendAction: "read",
      },
    ],
  },
  {
    id: "guests",
    label: "Guest & Visitor Tracking",
    category: "support",
    description: "Gate visitor logs, daytime guest approvals, and stay extensions",
    permissions: [
      {
        key: "guest_view",
        name: "View Guest & Visitor Logs",
        desc: "See all visitors inside property, check-in history, and tenant hosts",
        tier: "free",
        action: "view",
        backendFeatureKey: "guest_tracking",
        backendAction: "read",
      },
      {
        key: "guest_log",
        name: "Log Guest Entry & Exit",
        desc: "Record incoming visitor name, phone number, vehicle, and exit timestamp",
        tier: "free",
        action: "edit",
        backendFeatureKey: "guest_tracking",
        backendAction: "create",
      },
      {
        key: "guest_approve",
        name: "Approve Guest Stay Requests",
        desc: "Approve or reject visitor requests requested via the tenant app",
        tier: "free",
        action: "edit",
        backendFeatureKey: "guest_tracking",
        backendAction: "update",
      },
    ],
  },
  {
    id: "kyc",
    label: "KYC & Verification",
    category: "verification",
    description: "Aadhaar verification, government photo IDs, and police verification assist",
    permissions: [
      {
        key: "kyc_view",
        name: "View Tenant KYC Documents",
        desc: "View uploaded Aadhaar, driving license, passport, and student/work IDs",
        tier: "free",
        action: "view",
        backendFeatureKey: "digital_kyc",
        backendAction: "read",
      },
      {
        key: "kyc_approve",
        name: "Verify & Approve KYC",
        desc: "Mark tenant documents verified, request re-upload, or initiate DigiLocker",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "aadhaar_kyc",
        backendAction: "update",
      },
    ],
  },
  {
    id: "property",
    label: "Property Settings & Notices",
    category: "communication",
    description: "Digital notice board, WiFi credentials, house rules, and amenities",
    permissions: [
      {
        key: "property_view",
        name: "View Property Rules & Notices",
        desc: "View digital notices, WiFi network details, amenities, and house rules",
        tier: "free",
        action: "view",
        backendFeatureKey: "pg_notices",
        backendAction: "read",
      },
      {
        key: "property_edit",
        name: "Edit Rules, WiFi & Notices",
        desc: "Post property notices, modify WiFi passwords, and update PG amenities",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "pg_notices",
        backendAction: "update",
      },
    ],
  },
  {
    id: "refunds",
    label: "Refunds & Security Deposits",
    category: "payment",
    description: "Security deposit reconciliation, checkout deductions, and refund disbursement",
    permissions: [
      {
        key: "refund_view",
        name: "View Deposit Refunds",
        desc: "View deposit return requests, deductions, and processed refund receipts",
        tier: "lite",
        action: "view",
        backendFeatureKey: "security_deposit_tracking",
        backendAction: "read",
      },
      {
        key: "refund_add",
        name: "Process Deposit Refund",
        desc: "Calculate move-out deductions and record deposit refund to tenant",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "security_deposit_tracking",
        backendAction: "create",
      },
      {
        key: "refund_delete",
        name: "Delete / Void Refund",
        desc: "Remove an incorrect refund record from accounting balance",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "security_deposit_tracking",
        backendAction: "delete",
      },
    ],
  },
  {
    id: "eviction",
    label: "Notice Period & Evictions",
    category: "tenant_management",
    description: "Notice period pipeline, vacate dates, and formal eviction procedures",
    permissions: [
      {
        key: "eviction_view",
        name: "View Notice & Eviction Tracker",
        desc: "See tenants serving notice period, move-out dates, and eviction status",
        tier: "lite",
        action: "view",
        backendFeatureKey: "notice_period_management",
        backendAction: "read",
      },
      {
        key: "eviction_approve",
        name: "Initiate / Approve Eviction",
        desc: "Serve official eviction notice or confirm early tenant move-out",
        tier: "pro",
        action: "edit",
        backendFeatureKey: "notice_period_management",
        backendAction: "update",
      },
      {
        key: "eviction_cancel",
        name: "Cancel Eviction",
        desc: "Revoke an eviction notice and reinstate active tenant agreement",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "notice_period_management",
        backendAction: "delete",
      },
    ],
  },
  {
    id: "reports",
    label: "Reports & Financial Analytics",
    category: "reporting",
    description: "P&L statements, dues aging, occupancy trends, daily logs, and Excel exports",
    permissions: [
      {
        key: "dashboard_access",
        name: "View Analytics Dashboard",
        desc: "Access real-time property KPIs, occupancy rate, collection overview, and trends",
        tier: "free",
        action: "view",
        backendFeatureKey: "occupancy_dashboard",
        backendAction: "read",
      },
      {
        key: "report_people",
        name: "View People & Occupancy Reports",
        desc: "Access tenant rosters, historical move-in/outs, and room occupancy reports",
        tier: "free",
        action: "view",
        backendFeatureKey: "basic_reports",
        backendAction: "read",
      },
      {
        key: "report_daily",
        name: "View Daily Operations Report",
        desc: "Daily morning check: who paid, pending dues today, active complaints, checkouts",
        tier: "free",
        action: "view",
        backendFeatureKey: "basic_reports",
        backendAction: "read",
      },
      {
        key: "report_money",
        name: "View Financial & Revenue Reports",
        desc: "Access P&L, collection ledgers, dues aging, and revenue graphs (Hideable from staff)",
        tier: "lite",
        action: "view",
        backendFeatureKey: "collection_reports",
        backendAction: "read",
      },
      {
        key: "report_export",
        name: "Export Reports (Excel / PDF)",
        desc: "Download complete property data, rent ledgers, and tenant summaries",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "basic_reports",
        backendAction: "export",
      },
    ],
  },
  {
    id: "team",
    label: "Team, Staff & Roles",
    category: "tenant_management",
    description: "Property staff members, designations, role presets, and granular privileges",
    permissions: [
      {
        key: "team_view_members",
        name: "View Team Roster",
        desc: "See all staff, managers, caretakers, cleaners, and their contact information",
        tier: "free",
        action: "view",
        backendFeatureKey: "staff_management",
        backendAction: "read",
      },
      {
        key: "team_add_member",
        name: "Add New Staff Member",
        desc: "Invite new manager, caretaker, or cleaner and assign initial role",
        tier: "lite",
        action: "edit",
        backendFeatureKey: "staff_management",
        backendAction: "create",
      },
      {
        key: "team_edit_profile",
        name: "Edit Staff Role & Permissions",
        desc: "Customize granular view/edit switches, change designations, and reset credentials",
        tier: "pro",
        action: "edit",
        backendFeatureKey: "staff_roles_permissions",
        backendAction: "update",
      },
      {
        key: "team_property_access",
        name: "Manage Multi-PG Property Access",
        desc: "Assign staff to multiple PG properties and restrict cross-branch access",
        tier: "pro",
        action: "admin",
        backendFeatureKey: "staff_roles_permissions",
        backendAction: "update",
      },
    ],
  },
  {
    id: "group_chat",
    label: "PG Group Chat (PRO)",
    category: "communication",
    description: "Private verified PG-level broadcast and discussion group for tenants & staff",
    permissions: [
      {
        key: "chat_view",
        name: "View Group Chat & Messages",
        desc: "Access PG group chat room and read announcements and tenant conversations",
        tier: "pro",
        action: "view",
        backendFeatureKey: "pg_group_chat",
        backendAction: "read",
      },
      {
        key: "chat_member_view",
        name: "View Chat Member Roster",
        desc: "See list of active tenants, staff, and owner inside the PG group",
        tier: "pro",
        action: "view",
        backendFeatureKey: "pg_group_chat",
        backendAction: "read",
      },
      {
        key: "chat_send",
        name: "Send Messages in Chat",
        desc: "Send text messages and updates in the group feed",
        tier: "pro",
        action: "edit",
        backendFeatureKey: "pg_group_chat",
        backendAction: "create",
      },
      {
        key: "chat_reply",
        name: "Reply to Messages",
        desc: "Quote and reply directly to specific messages in the conversation",
        tier: "pro",
        action: "edit",
        backendFeatureKey: "pg_group_chat",
        backendAction: "create",
      },
      {
        key: "chat_media_upload",
        name: "Upload Photos & Attachments",
        desc: "Share photos, PDF notices, and documents in the chat",
        tier: "pro",
        action: "edit",
        backendFeatureKey: "pg_group_chat",
        backendAction: "create",
      },
      {
        key: "chat_pin",
        name: "Pin Group Announcements",
        desc: "Pin critical notices to the top banner of the PG group chat",
        tier: "pro",
        action: "edit",
        backendFeatureKey: "pg_group_chat",
        backendAction: "update",
      },
      {
        key: "chat_delete_own",
        name: "Delete Own Messages",
        desc: "Remove messages sent by oneself within allowed edit window",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "pg_group_chat",
        backendAction: "delete",
      },
      {
        key: "chat_delete_any",
        name: "Moderate / Delete Any Message",
        desc: "Delete inappropriate or spam messages sent by anyone in the group",
        tier: "pro",
        action: "delete",
        backendFeatureKey: "pg_group_chat",
        backendAction: "delete",
      },
      {
        key: "chat_group_settings",
        name: "Manage Group Settings",
        desc: "Mute non-admin messages, toggle member posting, and configure chat rules",
        tier: "pro",
        action: "admin",
        backendFeatureKey: "pg_group_chat",
        backendAction: "update",
      },
    ],
  },
  {
    id: "app_access",
    label: "App & Security Portals",
    category: "automation",
    description: "Mobile app login, guard security portal, and tenant view modes",
    permissions: [
      {
        key: "app_mobile_view",
        name: "Mobile App Access",
        desc: "Staff can log in and manage tasks through the PG Ease mobile app",
        tier: "free",
        action: "view",
        backendFeatureKey: "staff_basic_access",
        backendAction: "read",
      },
      {
        key: "app_guard_view",
        name: "Gate & Guard Terminal Mode",
        desc: "Simplified security terminal for gate check-in, check-out, and visitor entry",
        tier: "free",
        action: "view",
        backendFeatureKey: "staff_basic_access",
        backendAction: "read",
      },
      {
        key: "app_member_view",
        name: "Tenant Experience Preview",
        desc: "Preview food menu, notices, and billing as seen by a tenant",
        tier: "free",
        action: "view",
        backendFeatureKey: "tenant_app_access",
        backendAction: "read",
      },
    ],
  },
];
