export type PresetCell = true | false | "always";

export const ROLE_PRESETS: Record<string, Record<string, PresetCell>> = {
  manager: {
    app_mobile_view: "always",
    app_guard_view: false,
    app_member_view: true,
    room_view: "always",
    room_add: true,
    room_edit: true,
    room_delete: false,
    complaint_view_all: "always",
    complaint_edit_assign: true,
    complaint_raise: "always",
    complaint_view_own: "always",
    complaint_edit_own: true,
    food_view_edit: "always",
    account_view_dues: "always",
    account_send_reminders: true,
    account_view_own_dues: "always",
    account_record_payment: true,
    account_otp_cash: true,
    account_edit_dues: true,
    account_delete_dues: false,
    account_add_dues: true,
    expense_view: "always",
    expense_add: true,
    expense_edit: true,
    expense_delete: false,
    tenant_view: "always",
    tenant_add: true,
    tenant_edit_basic: true,
    tenant_edit_rental: true,
    tenant_change_room: true,
    tenant_delete: false,
    tenant_delete_old: false,
    tenant_opening_balance: true,
    report_people: "always",
    report_money: true,
    report_daily: "always",
    refund_add: true,
    refund_delete: false,
    dashboard_access: "always",
    eviction_approve: true,
    eviction_cancel: true,
    nightout_view: "always",
    nightout_approve: true,
    nightout_mark_returned: "always",
    nightout_extend: true,
    outing_approve: true,
    nightout_report: true,
    attend_mark: true,
    attend_view: "always",
    attend_leave: true,
    guest_log: true,
    guest_approve: true,
    kyc_view: "always",
    kyc_approve: true,
    team_view_members: "always",
    team_edit_profile: false,
    team_property_access: true,
  },
  caretaker: {
    app_mobile_view: "always",
    app_guard_view: true,
    app_member_view: false,
    room_view: "always",
    complaint_view_all: true,
    complaint_raise: "always",
    complaint_view_own: "always",
    complaint_edit_own: true,
    food_view_edit: "always",
    account_view_own_dues: true,
    tenant_view: true,
    tenant_edit_basic: true,
    report_daily: true,
    nightout_view: true,
    nightout_mark_returned: "always",
    attend_mark: "always",
    attend_view: true,
    guest_log: "always",
  },
  cleaner: {
    app_mobile_view: "always",
    complaint_raise: "always",
    complaint_view_own: "always",
    complaint_edit_own: true,
    food_view_edit: true,
  },
  warden: {
    app_mobile_view: "always",
    app_guard_view: "always",
    app_member_view: true,
    room_view: "always",
    complaint_view_all: true,
    complaint_raise: "always",
    complaint_view_own: "always",
    nightout_view: "always",
    nightout_approve: true,
    nightout_mark_returned: "always",
    nightout_extend: true,
    outing_approve: true,
    attend_mark: "always",
    attend_view: "always",
    attend_leave: true,
    guest_log: "always",
    guest_approve: true,
    eviction_approve: true,
    kyc_view: false,
  },
};

export const ROLE_LABELS: Record<string, { title: string; desc: string }> = {
  manager: {
    title: "Manager",
    desc: "Full operations access — finance, tenants, reports",
  },
  caretaker: {
    title: "Caretaker",
    desc: "Ground-level — rooms, food, attendance, complaints",
  },
  cleaner: {
    title: "Cleaner",
    desc: "Minimal — complaints & food menu only",
  },
  warden: {
    title: "Warden",
    desc: "Security — gate, guests, night out, attendance",
  },
};
