import type { HttpMethod } from "@/api/http";

/** Mirrors `API_BASE_URL` in `src/api/http.ts` (display only). */
export const DOCUMENTED_API_BASE = "https://pg-ease-nest.vercel.app/api";

export interface ImplementedApiRow {
  clientExport: string;
  method: HttpMethod;
  /** Path after `/api` (leading slash, `:id` placeholders). */
  path: string;
  auth: boolean;
  useCase: string;
  /** Section heading on the catalog page (product flow order). */
  flowPhase: string;
  /**
   * Primary in-app URL for this call. Empty string means there is no dedicated screen
   * (background refresh, unused client, or shared infrastructure).
   */
  appRoute: string;
  /** How to reach and trigger this API in the product. */
  steps: string[];
}

/** Section order for the reference page (matches typical owner journey). */
export const API_FLOW_PHASE_ORDER: string[] = [
  "Login & session",
  "Onboarding & first PG",
  "App shell",
  "Dashboard",
  "My PGs",
  "Structure (blocks, floors & rooms)",
  "Tenants",
  "Rent payments",
  "Complaints",
  "Tenant KYC",
  "Team",
  "Legacy staff",
  "Roles & permissions",
  "Reports",
  "Plans & pricing",
  "Settings",
  "Utilities & background",
];

/**
 * Inventory of HTTP endpoints this app calls, ordered by product flow (not alphabetically).
 */
export const IMPLEMENTED_API_CATALOG: ImplementedApiRow[] = [
  {
    clientExport: "requestOtp",
    method: "POST",
    path: "/property-owners/otp/request",
    auth: false,
    useCase: "Send an OTP SMS to the owner’s mobile.",
    flowPhase: "Login & session",
    appRoute: "/login",
    steps: [
      "Open `/login` (or `/` when logged out).",
      "Enter your mobile number.",
      "Request OTP — this calls `requestOtp`.",
    ],
  },
  {
    clientExport: "verifyOtp",
    method: "POST",
    path: "/property-owners/otp/verify",
    auth: false,
    useCase: "Verify OTP and store access + refresh tokens.",
    flowPhase: "Login & session",
    appRoute: "/login",
    steps: [
      "On `/login`, after OTP is sent, enter the code you received.",
      "Submit — this calls `verifyOtp` and redirects into the app or onboarding.",
    ],
  },
  {
    clientExport: "attemptTokenRefresh (http.ts)",
    method: "POST",
    path: "/property-owners/refresh-token",
    auth: false,
    useCase: "Renew the session when a protected request returns 401.",
    flowPhase: "Login & session",
    appRoute: "",
    steps: [
      "Use any authenticated screen after login.",
      "When the access token expires, the next API call triggers a silent refresh (no button).",
      "If refresh fails, you are redirected to `/login`.",
    ],
  },
  {
    clientExport: "getPropertyTypesAndAmenities",
    method: "GET",
    path: "/property-owners/property-type-and-amenities",
    auth: true,
    useCase: "Load property types and master amenities for the wizard.",
    flowPhase: "Onboarding & first PG",
    appRoute: "/onboarding",
    steps: [
      "After first login, open `/onboarding` (or follow the redirect).",
      "The wizard loads catalog data for property type and amenities.",
    ],
  },
  {
    clientExport: "createProperty",
    method: "POST",
    path: "/property-owners/properties",
    auth: true,
    useCase: "Create your first (or additional) PG record.",
    flowPhase: "Onboarding & first PG",
    appRoute: "/onboarding",
    steps: [
      "On `/onboarding`, complete location and PG detail steps.",
      "Finish the wizard — submit creates the property via `createProperty`.",
    ],
  },
  {
    clientExport: "getProperties",
    method: "GET",
    path: "/property-owners/properties",
    auth: true,
    useCase: "Load all PGs for the header selector and app context.",
    flowPhase: "App shell",
    appRoute: "/dashboard",
    steps: [
      "Sign in so you land inside the main layout.",
      "The app fetches your PG list on load (e.g. open `/dashboard` or any app page).",
      "Pick a PG from the header selector — context uses the returned ids.",
    ],
  },
  {
    clientExport: "updateLanguage",
    method: "POST",
    path: "/property-owners/language",
    auth: true,
    useCase: "Persist account language (Hindi / English) to the backend.",
    flowPhase: "App shell",
    appRoute: "/settings",
    steps: [
      "Either: during `/onboarding`, choose language when the step offers it.",
      "Or: open `/settings` and change language — both paths call `updateLanguage`.",
    ],
  },
  {
    clientExport: "getAllRoomsAndCounts",
    method: "GET",
    path: "/property-owners/all-rooms-and-counts/:propertyId",
    auth: true,
    useCase: "Bed and vacancy aggregates for dashboard cards.",
    flowPhase: "Dashboard",
    appRoute: "/dashboard",
    steps: [
      "Open `/dashboard` or `/kpis` from the sidebar.",
      "Select a PG in the header if prompted.",
      "Overview loads room/bed stats for the selected property.",
    ],
  },
  {
    clientExport: "getAllStaffWithPermissions",
    method: "GET",
    path: "/property-owners/get-all-staff-with-permissions/:propertyId",
    auth: true,
    useCase: "Staff roster with permissions (dashboard headcount and legacy staff table).",
    flowPhase: "Dashboard",
    appRoute: "/dashboard",
    steps: [
      "Open `/dashboard` with a PG selected — staff summary uses this API.",
      "The same endpoint powers the roster on **Legacy staff** (`/staff`) when you manage staff there.",
    ],
  },
  {
    clientExport: "getDashboardDetails",
    method: "GET",
    path: "/property-owners/dashboard-details/:propertyId",
    auth: true,
    useCase: "Property-scoped dashboard detail payload.",
    flowPhase: "Dashboard",
    appRoute: "/dashboard",
    steps: [
      "Open `/dashboard` or `/kpis`.",
      "Ensure a PG is selected — details query runs for that `propertyId`.",
    ],
  },
  {
    clientExport: "getDashboardKpis",
    method: "GET",
    path: "/property-owners/dashboard/kpis",
    auth: true,
    useCase: "Global KPI strip for the owner dashboard.",
    flowPhase: "Dashboard",
    appRoute: "/kpis",
    steps: [
      "From the sidebar under Dashboard, open **KPIs** (`/kpis`).",
      "KPI widgets load using this endpoint (also available from the main dashboard route).",
    ],
  },
  {
    clientExport: "getPropertyAmenities",
    method: "GET",
    path: "/property-owners/properties/:propertyId/amenities",
    auth: true,
    useCase: "List amenities linked to the PG.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "Sidebar → **My PGs** → **PG Details** (`/my-pgs`).",
      "Select the correct PG in the header.",
      "Open the amenities section — data loads for editing.",
    ],
  },
  {
    clientExport: "createCustomAmenity",
    method: "POST",
    path: "/property-owners/properties/:propertyId/amenities/custom",
    auth: true,
    useCase: "Add a custom amenity label.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "On `/my-pgs`, find the custom amenity input.",
      "Enter a name and add — triggers `createCustomAmenity`.",
    ],
  },
  {
    clientExport: "linkAmenities",
    method: "PUT",
    path: "/property-owners/properties/:propertyId/amenities",
    auth: true,
    useCase: "Save selected amenity ids for the PG.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "On `/my-pgs`, tick amenities you offer.",
      "Save the amenities section — calls `linkAmenities`.",
    ],
  },
  {
    clientExport: "getPropertyRestrictions",
    method: "GET",
    path: "/property-owners/properties/:propertyId/restrictions",
    auth: true,
    useCase: "List house rules / restrictions.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "Open `/my-pgs` with your PG selected.",
      "Scroll to restrictions — list loads from this API.",
    ],
  },
  {
    clientExport: "createCustomRestriction",
    method: "POST",
    path: "/property-owners/properties/:propertyId/restrictions/custom",
    auth: true,
    useCase: "Add a custom restriction.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "On `/my-pgs`, use the custom restriction field.",
      "Submit to create via `createCustomRestriction`.",
    ],
  },
  {
    clientExport: "linkRestrictions",
    method: "PUT",
    path: "/property-owners/properties/:propertyId/restrictions",
    auth: true,
    useCase: "Save selected restriction ids.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "On `/my-pgs`, select restrictions that apply.",
      "Save — persists with `linkRestrictions`.",
    ],
  },
  {
    clientExport: "getDiningSchedule",
    method: "GET",
    path: "/property-owners/properties/:propertyId/dining-schedule",
    auth: true,
    useCase: "Load weekly mess / dining schedule.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "Open `/my-pgs` (PG details).",
      "Open the dining / mess schedule section to load existing slots.",
    ],
  },
  {
    clientExport: "updateDiningSchedule",
    method: "PUT",
    path: "/property-owners/properties/:propertyId/dining-schedule",
    auth: true,
    useCase: "Save dining slots for the week.",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "On `/my-pgs`, edit breakfast / lunch / dinner fields.",
      "Save the dining section — calls `updateDiningSchedule`.",
    ],
  },
  {
    clientExport: "updateProperty",
    method: "PUT",
    path: "/property-owners/properties/:propertyId",
    auth: true,
    useCase: "Update PG profile (name, address, geo, pin, bed range, type, photos payload).",
    flowPhase: "My PGs",
    appRoute: "/my-pgs",
    steps: [
      "Go to `/my-pgs` and edit PG name, address, pin, coordinates, bed range, or type.",
      "Save PG details — uses `updateProperty`.",
    ],
  },
  {
    clientExport: "getBlocks",
    method: "GET",
    path: "/property-owners/properties/:propertyId/blocks",
    auth: true,
    useCase: "List blocks for structure and tenant pickers.",
    flowPhase: "Structure (blocks, floors & rooms)",
    appRoute: "/my-pgs/structure",
    steps: [
      "Sidebar → **My PGs** → **Blocks, Floors & Rooms** (`/my-pgs/structure`).",
      "Select your PG — blocks load for that property.",
    ],
  },
  {
    clientExport: "createBlock",
    method: "POST",
    path: "/property-owners/properties/:propertyId/blocks",
    auth: true,
    useCase: "Create a new block.",
    flowPhase: "Structure (blocks, floors & rooms)",
    appRoute: "/my-pgs/structure",
    steps: [
      "On `/my-pgs/structure`, use add block.",
      "Enter a block name and confirm.",
    ],
  },
  {
    clientExport: "getFloors",
    method: "GET",
    path: "/property-owners/properties/:propertyId/blocks/:blockId/floors",
    auth: true,
    useCase: "List floors under a block.",
    flowPhase: "Structure (blocks, floors & rooms)",
    appRoute: "/my-pgs/structure",
    steps: [
      "On `/my-pgs/structure`, pick a block.",
      "Floors load for that block.",
    ],
  },
  {
    clientExport: "createFloor",
    method: "POST",
    path: "/property-owners/properties/:propertyId/blocks/:blockId/floors",
    auth: true,
    useCase: "Create a floor under a block.",
    flowPhase: "Structure (blocks, floors & rooms)",
    appRoute: "/my-pgs/structure",
    steps: [
      "On `/my-pgs/structure`, select a block then add floor.",
      "Submit the floor name.",
    ],
  },
  {
    clientExport: "getRooms",
    method: "GET",
    path: "/property-owners/properties/:propertyId/rooms",
    auth: true,
    useCase: "Paginated / filtered room grid.",
    flowPhase: "Structure (blocks, floors & rooms)",
    appRoute: "/my-pgs/structure",
    steps: [
      "On `/my-pgs/structure`, choose block/floor filters as provided.",
      "Rooms table refreshes from `getRooms` (pagination params when used).",
    ],
  },
  {
    clientExport: "getRoomsList",
    method: "GET",
    path: "/property-owners/properties/:propertyId/rooms/list",
    auth: true,
    useCase: "Lightweight room list for filters.",
    flowPhase: "Structure (blocks, floors & rooms)",
    appRoute: "/my-pgs/structure",
    steps: [
      "Used from structure flows when a compact room list is needed.",
      "Stay on `/my-pgs/structure` with PG selected and use UI that loads room lists.",
    ],
  },
  {
    clientExport: "createRoom",
    method: "POST",
    path: "/property-owners/properties/:propertyId/rooms",
    auth: true,
    useCase: "Add a room with beds and optional rent-by-sharing.",
    flowPhase: "Structure (blocks, floors & rooms)",
    appRoute: "/my-pgs/structure",
    steps: [
      "On `/my-pgs/structure`, open add room for a floor.",
      "Fill room number, bed count, optional pricing, then save.",
    ],
  },
  {
    clientExport: "getPropertyTenants",
    method: "GET",
    path: "/property-owners/properties/:propertyId/tenants",
    auth: true,
    useCase: "Tenant list with room and bed context.",
    flowPhase: "Tenants",
    appRoute: "/tenants",
    steps: [
      "Sidebar → **Tenants** → **Tenant List** (`/tenants`).",
      "Select the PG in the header — tenant rows load.",
    ],
  },
  {
    clientExport: "addTenant",
    method: "POST",
    path: "/property-owners/add-tenant/:propertyId",
    auth: true,
    useCase: "Allocate a tenant to a bed.",
    flowPhase: "Tenants",
    appRoute: "/tenants",
    steps: [
      "On `/tenants`, click add tenant (or open the add dialog from dashboard quick action).",
      "Pick block, floor, room, bed, rent fields, then submit.",
    ],
  },
  {
    clientExport: "updatePropertyTenant",
    method: "PATCH",
    path: "/property-owners/properties/:propertyId/tenants/:tenantId",
    auth: true,
    useCase: "Update tenant name, phone, or email.",
    flowPhase: "Tenants",
    appRoute: "/tenants",
    steps: [
      "On `/tenants`, open a tenant’s detail dialog.",
      "Edit profile fields and save.",
    ],
  },
  {
    clientExport: "getRentCollectionDashboard",
    method: "GET",
    path: "/property-owners/properties/:propertyId/rent-collections/dashboard",
    auth: true,
    useCase: "Monthly rent dashboard (paid vs unpaid).",
    flowPhase: "Rent payments",
    appRoute: "/rent-payments",
    steps: [
      "Sidebar → **Payments** → **Rent Collection** (`/rent-payments`).",
      "Pick month/year and PG — dashboard loads tenant payment rows.",
    ],
  },
  {
    clientExport: "postManualRentCollection",
    method: "POST",
    path: "/property-owners/properties/:propertyId/rent-collections/manual",
    auth: true,
    useCase: "Record a manual / offline rent payment.",
    flowPhase: "Rent payments",
    appRoute: "/rent-payments",
    steps: [
      "On `/rent-payments`, use the UI action to record a payment for a tenant period.",
      "Confirm amount and period — submits manual collection.",
    ],
  },
  {
    clientExport: "getComplaintsByProperty",
    method: "GET",
    path: "/property-owners/properties/:propertyId/complaints",
    auth: true,
    useCase: "Complaints list (full workspace and dashboard complaint summaries).",
    flowPhase: "Complaints",
    appRoute: "/complaints",
    steps: [
      "Primary: sidebar → **Complaints** (`/complaints`) with a PG selected — the table loads here.",
      "The same request also runs on **`/dashboard`** (and `/kpis`) for complaint count widgets.",
    ],
  },
  {
    clientExport: "updateComplaintStatus",
    method: "PUT",
    path: "/property-owners/complaints/:complaintId",
    auth: true,
    useCase: "Change complaint status or add remarks.",
    flowPhase: "Complaints",
    appRoute: "/complaints",
    steps: [
      "On `/complaints`, open a complaint or use status controls.",
      "Save status / remarks — calls `updateComplaintStatus`.",
    ],
  },
  {
    clientExport: "getKycApplications",
    method: "GET",
    path: "/property-owners/kyc/applications",
    auth: true,
    useCase: "Queue of KYC applications.",
    flowPhase: "Tenant KYC",
    appRoute: "/tenants/kyc",
    steps: [
      "Sidebar → **Tenants** → **Tenant KYC** (`/tenants/kyc`).",
      "Applications list loads on entry.",
    ],
  },
  {
    clientExport: "getKycByRoomTenantId",
    method: "GET",
    path: "/property-owners/kyc/:roomTenantId",
    auth: true,
    useCase: "Single KYC record for review.",
    flowPhase: "Tenant KYC",
    appRoute: "/tenants/kyc",
    steps: [
      "On `/tenants/kyc`, select or drill into one application.",
      "Detail fetch uses the room-tenant id from the row.",
    ],
  },
  {
    clientExport: "approveKycApplication",
    method: "PATCH",
    path: "/property-owners/kyc/:roomTenantId/approve",
    auth: true,
    useCase: "Approve a KYC submission.",
    flowPhase: "Tenant KYC",
    appRoute: "/tenants/kyc",
    steps: [
      "On `/tenants/kyc`, open an application.",
      "Use approve — calls `approveKycApplication`.",
    ],
  },
  {
    clientExport: "rejectKycApplication",
    method: "PATCH",
    path: "/property-owners/kyc/:roomTenantId/reject",
    auth: true,
    useCase: "Reject KYC with a reason.",
    flowPhase: "Tenant KYC",
    appRoute: "/tenants/kyc",
    steps: [
      "On `/tenants/kyc`, open an application.",
      "Choose reject and enter a reason when prompted.",
    ],
  },
  {
    clientExport: "listStaff",
    method: "GET",
    path: "/staff",
    auth: true,
    useCase: "Legacy-format staff list (optional `pgId` query).",
    flowPhase: "Team",
    appRoute: "/team",
    steps: [
      "Sidebar → **Team** → **Team list** (`/team`).",
      "The list loads for the current / selected PG context.",
    ],
  },
  {
    clientExport: "createStaff (staff)",
    method: "POST",
    path: "/staff",
    auth: true,
    useCase: "Create staff via the newer `/staff` API.",
    flowPhase: "Team",
    appRoute: "/team/add-staff",
    steps: [
      "Sidebar → **Team** → open **Add staff** (`/team/add-staff`).",
      "Fill the form and submit — creates the staff record.",
    ],
  },
  {
    clientExport: "getStaff",
    method: "GET",
    path: "/staff/:staffId",
    auth: true,
    useCase: "Load one staff record for editing.",
    flowPhase: "Team",
    appRoute: "/team",
    steps: [
      "Open **Team list** (`/team`), click a staff member.",
      "Open **Permissions** — the URL becomes `/team/<staffId>/permissions`; this fetch runs for that id.",
    ],
  },
  {
    clientExport: "patchStaffPermissions",
    method: "PATCH",
    path: "/staff/:staffId/permissions",
    auth: true,
    useCase: "Replace permission keys for a staff member.",
    flowPhase: "Team",
    appRoute: "/team",
    steps: [
      "From `/team`, open `/team/<staffId>/permissions` for that person.",
      "Toggle permission keys and save — triggers `patchStaffPermissions`.",
    ],
  },
  {
    clientExport: "getDesignations",
    method: "GET",
    path: "/property-owners/designations",
    auth: true,
    useCase: "Designation dropdown values.",
    flowPhase: "Legacy staff",
    appRoute: "/staff",
    steps: [
      "Open `/staff` and start **Add staff** dialog.",
      "Designation select options come from `getDesignations`.",
    ],
  },
  {
    clientExport: "createStaff (propertyOwner)",
    method: "POST",
    path: "/property-owners/create-staff",
    auth: true,
    useCase: "Create staff via property-owner endpoint (legacy dialog).",
    flowPhase: "Legacy staff",
    appRoute: "/staff",
    steps: [
      "On `/staff`, open add staff and submit the legacy form.",
      "Uses `createStaff` from the property-owner API module.",
    ],
  },
  {
    clientExport: "getStaffPermissions",
    method: "GET",
    path: "/property-owners/staff/permissions",
    auth: true,
    useCase: "Master permission list for role builder.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "Sidebar → **Team** → **Roles & Permissions** (`/staff/roles`).",
      "Permission catalog loads for tier linking.",
    ],
  },
  {
    clientExport: "getStaffPermissionsById",
    method: "GET",
    path: "/property-owners/staff/:staffId/permissions",
    auth: true,
    useCase: "Permissions attached to one staff id.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, pick a staff member in the relevant control.",
      "Their assigned permissions load for review.",
    ],
  },
  {
    clientExport: "staffPermissionsAssign",
    method: "POST",
    path: "/property-owners/staff/permissions/assign/:staffId",
    auth: true,
    useCase: "Assign a named permission bundle to staff.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, use assign permissions / bundle actions for a staff id.",
      "Submit the assignment form.",
    ],
  },
  {
    clientExport: "updateStaffPermissions",
    method: "POST",
    path: "/property-owners/update-staff-permissions/:staffId",
    auth: true,
    useCase: "Bulk-update staff permission ids.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, adjust permission checkboxes for a user.",
      "Save bulk update when the UI exposes it.",
    ],
  },
  {
    clientExport: "getStaffPermissionTiers",
    method: "GET",
    path: "/property-owners/staff/permission-tiers",
    auth: true,
    useCase: "List permission tiers.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "Open `/staff/roles` — tier list populates dropdowns and tables.",
    ],
  },
  {
    clientExport: "createStaffPermissionTier",
    method: "POST",
    path: "/property-owners/staff/permission-tiers",
    auth: true,
    useCase: "Create a new permission tier.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, use create tier (name / description).",
      "Submit the tier form.",
    ],
  },
  {
    clientExport: "linkPermissionToStaffTier",
    method: "POST",
    path: "/property-owners/staff/permission-tiers/:tierId/permissions/:permissionId",
    auth: true,
    useCase: "Attach one permission to a tier.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, choose tier and permission to link.",
      "Run the link action — hits this route.",
    ],
  },
  {
    clientExport: "assignStaffRole",
    method: "POST",
    path: "/property-owners/staff/roles/assign",
    auth: true,
    useCase: "Assign a staff member to a permission tier.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, pick staff and target tier.",
      "Submit role assignment.",
    ],
  },
  {
    clientExport: "getStaffMemberRoles",
    method: "GET",
    path: "/property-owners/staff/:staffId/roles",
    auth: true,
    useCase: "Roles currently attached to a staff member.",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, select a staff member to inspect roles.",
      "Role membership loads from this endpoint.",
    ],
  },
  {
    clientExport: "createStaffPermissionDefinition",
    method: "POST",
    path: "/property-owners/staff/permissions",
    auth: true,
    useCase: "Create a staff-scoped permission definition (admin-style).",
    flowPhase: "Roles & permissions",
    appRoute: "/staff/roles",
    steps: [
      "On `/staff/roles`, use the advanced / definition form if shown.",
      "Submit to create a new permission row.",
    ],
  },
  {
    clientExport: "getAnalyticsPgGrowth",
    method: "GET",
    path: "/property-owners/analytics/pg-growth",
    auth: true,
    useCase: "Portfolio PG growth JSON for reports.",
    flowPhase: "Reports",
    appRoute: "/reports",
    steps: [
      "Sidebar → **Reports** (`/reports` or child routes).",
      "Growth panel loads when that section is visible.",
    ],
  },
  {
    clientExport: "getAnalyticsRevenue",
    method: "GET",
    path: "/property-owners/analytics/revenue",
    auth: true,
    useCase: "Revenue analytics for selected PG.",
    flowPhase: "Reports",
    appRoute: "/reports",
    steps: [
      "Open `/reports` with a PG selected.",
      "Revenue analytics card fetches with `propertyId` query.",
    ],
  },
  {
    clientExport: "getAnalyticsOccupancy",
    method: "GET",
    path: "/property-owners/analytics/occupancy",
    auth: true,
    useCase: "Occupancy analytics for selected PG.",
    flowPhase: "Reports",
    appRoute: "/reports",
    steps: [
      "Open `/reports` with a PG selected.",
      "Occupancy analytics uses `propertyId` query.",
    ],
  },
  {
    clientExport: "getMyFeatures",
    method: "GET",
    path: "/property-owners/my-features",
    auth: true,
    useCase: "Subscription plan and entitlements for gating.",
    flowPhase: "Plans & pricing",
    appRoute: "/plans",
    steps: [
      "Sidebar → **Plans & Pricing** (`/plans`) — plan and feature list load here.",
      "The same endpoint is also called from **Legacy staff** (`/staff`) for staff-related feature checks.",
    ],
  },
  {
    clientExport: "getMe",
    method: "GET",
    path: "/property-owners/me",
    auth: true,
    useCase: "Refresh logged-in owner profile.",
    flowPhase: "Settings",
    appRoute: "/settings",
    steps: [
      "Open `/settings` (Profile).",
      "Pull to refresh or use Retry — refetches `getMe`.",
    ],
  },
  {
    clientExport: "uploadPhoto",
    method: "POST",
    path: "/property-owners/upload-photo",
    auth: true,
    useCase: "Upload an image file and receive a hosted URL.",
    flowPhase: "Settings",
    appRoute: "/settings",
    steps: [
      "On `/settings`, use the profile photo upload control.",
      "Choose a file — multipart upload runs via `uploadPhoto`.",
    ],
  },
  {
    clientExport: "refreshToken",
    method: "POST",
    path: "/property-owners/refresh-token",
    auth: false,
    useCase: "Explicit token rotation using the stored refresh token (same URL as automatic refresh).",
    flowPhase: "Utilities & background",
    appRoute: "",
    steps: [
      "Exported as `refreshToken` on the property-owner client for manual use if you wire it.",
      "Day-to-day sessions rely on the automatic refresh in `http.ts` instead.",
    ],
  },
  {
    clientExport: "deleteStaff",
    method: "DELETE",
    path: "/staff/:staffId",
    auth: true,
    useCase: "Delete a staff member (client ready; UI hookup optional).",
    flowPhase: "Utilities & background",
    appRoute: "",
    steps: [
      "Implemented in the staff API client — no primary delete button in the UI yet.",
      "When delete is added, expect it from `/team` or `/staff` row actions.",
    ],
  },
];

export function catalogGroupedByFlow(): { phase: string; items: ImplementedApiRow[] }[] {
  const map = new Map<string, ImplementedApiRow[]>();
  for (const phase of API_FLOW_PHASE_ORDER) {
    map.set(phase, []);
  }
  for (const row of IMPLEMENTED_API_CATALOG) {
    const bucket = map.get(row.flowPhase);
    if (bucket) bucket.push(row);
    else {
      const misc = map.get("Utilities & background") ?? [];
      misc.push(row);
      map.set("Utilities & background", misc);
    }
  }
  return API_FLOW_PHASE_ORDER.filter((p) => (map.get(p)?.length ?? 0) > 0).map((p) => ({
    phase: p,
    items: map.get(p)!,
  }));
}
